(misc): Update
+ Make extract echo out when extractor not found
+ Add exchange-rate script to hledger
+ Add aliases for nordvpn
+ Add a nord-reset command

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -52,6 +52,10 @@ while read -r path; do
     *.rar|*.cbr)                     unrar x    "$path" ;;
     *.cab)                           cabextract "$path" ;;
     *.cb7|*.7z|*.c7z)                7z x       "$path" ;;
+    *.zst)                           unzstd     "$path" ;;
+    *) echo "error: extract: unknown archive format: $path" >&2
+       exit_code=1
+       ;;
   esac || exit_code=1
 done <<< "$(printf "%s\n" "$@")"
 
