(bin): Make find-project support multiple dirs
Now you can pass multiple paths to find-project to have it list multiple
project-files at once. This makes find a good replacement for existing
recursive ls like commands such as rg or fd.

diff --git a/bin/find-project b/bin/find-project
--- a/bin/find-project
+++ b/bin/find-project
@@ -2,20 +2,19 @@
 # Recursively find files in the current project directory.
 #
 # Uses a host of different programs to find ways to respect ignore
-# files (such as .gitignore or .ignore etc.).
+# files (such as .gitignore, .ignore etc.).
 
-set -e # auto exit on a failed command
+read -r -d '' USAGE <<EOF
+Usage: find-project [-h] [-d|-f] [-z] [-c|-C] [-a] [-v] [DIR [...DIR]]
+EOF
 
-function print_usage {
-    echo "Usage: find-project [-h] [-d|-f] [-z] [-c|-C] [DIR]"
-}
+read -r -d '' HELP <<EOF
+$USAGE
 
-function print_help {
-    print_usage
-    cat <<-EOF
-
-  Recursively list all the files in a project.
-  Listing all files if the CWD isn't a project.
+  Recursively list all the files in a project, respecting any
+  ignore configurations using tools that support them. When
+  a directory being listed isn't a project this script lists
+  all the files in it.
 
 Optional arguments:
   -h      show this help message and exit
@@ -24,56 +23,74 @@ Optional arguments:
   -a      skip project check and list all files
   -u/-U   guarantee the paths are outputted uniquely
   -c/-C   color paths using same format as LS_COLORS
+  -v      Don't hide debugging output from listing
 EOF
-}
 
-dirs_only=0 files_only=0 null=0 find_all=0 uniquify=1 color=0
-while getopts 'cChdfzauU' OPTION; do
+set -e # auto exit on a failed command
+
+dirs_only=0 files_only=0 null=0 find_all=0 color=0 verbose=0
+while getopts 'cChdfzav' OPTION; do
     case "$OPTION" in
-        h) print_help
-           exit 0
-           ;;
-        \?) print_usage >&2
-            exit 1
-            ;;
+        h) echo "$HELP"
+           exit 0 ;;
+        \?) echo "$USAGE" >&2
+            exit 1 ;;
         d) dirs_only=1 ;;
         f) files_only=1 ;;
         z) null=1 ;;
         a) find_all=1 ;;
-        u) uniquify=1 ;;
-        U) uniquify=0 ;;
         c) color=1 ;;
         C) color=0 ;;
+        v) verbose=1 ;;
     esac
 done
 shift "$((OPTIND-1))"
-[ -n "$*" ] && cwd="$*" || cwd="./"
+if [ -z "$*" ]; then
+    dirs=( "./" )
+fi
+dirs=( "$@" )
+
+[ "$verbose" -eq 0 ] && exec 2>/dev/null
+
+# Gawk arguments to load $dirs into a gawk subprocess.
+gawk_pre_dirs=(
+    -v paths_str="$(IFS=:; echo "${dirs[*]}")"
+    -e 'BEGIN {
+  for (i=1; i <= split(paths_str, paths_arr, ":"); i++) {
+    gsub("/*$", "", paths_arr[i])
+    dirs[paths_arr[i]]++
+  }
+}'
+)
 
 # ┌───────────────────┐
 # │ Utility Functions │
 # └───────────────────┘
 
-function files_to_dir {
-    # strip out filename components, removing all but the filename.
-    # WARN: there's this weird issue were some paths lead xargs to give out
+files_to_dir() {
+    # Strip out filename components, removing all but the filename.
+    #
+    # WARN: There's this weird issue were some paths lead xargs to give out
     #       two lines, one ending with a / and the other beginning with a .
     #       For now I'm just stripping both these out, but I should probably
     #       come up with a better solution.
-    xargs -d '\n' -r dirname {} + |
-        awk -v cwd="$cwd" \
-            -e '!($0 ~ /^\.$/ || $0 ~ /^\/$/ || match(cwd, $0))' |
-        if [ "$uniquify" -eq 1 ]; then awk '!seen[$0]++'; else cat; fi
+    xargs -d '\n' -r dirname |
+        awk "${gawk_pre_dirs[@]}" \
+            -e '!($0 == "." || $0 ~ /^\/$/ || dirs[$0]++)'
 }
 
-function files_to_files_and_dir {
-    # for each file in STDIN, read the directory component and echo
-    # it out seperately. each directory is only outputted once.
-    awk -v cwd="$cwd" \
+files_to_files_and_dir() {
+    # For each file in STDIN, read the directory component and echo
+    # it out seperately. Each directory is only outputted once such
+    # that repeated files in the same directory don't cause non-unique
+    # directory outputs.
+    awk "${gawk_pre_dirs[@]}" \
         -e '
 {
   if (match($0, /(.+)\/[^\/]+$/, group)) {
     dir = group[1]
-    if (dir != "." && !dirs[dir]++ && !match(cwd, dir)) {
+    # If not cwd and not seen before.
+    if (dir != "." && !dirs[dir]++) {
       print dir "/"
     }
   }
@@ -89,7 +106,7 @@ function files_to_files_and_dir {
 # Filters accept file paths from stdin and transform them depending
 # on the environment of the current script.
 
-function file_filter {
+file_filter() {
     # Given a stream of file paths, this filter either filters out the
     # basename component or zips together directories and files in the
     # output.
@@ -102,23 +119,41 @@ function file_filter {
     fi
 }
 
-function null_filter() {
-    if [ "$null" -eq 1 ]; then tr '\n' '\0'; else cat; fi
+null_filter() {
+    if [ "$null" -eq 1 ]; then
+        tr '\n' '\0'
+    else
+        cat
+    fi
+}
+
+color_filter() {
+    if [ "$color" -eq 0 ]; then
+        cat # no color, output as is :-(
+    elif hash parallel; then
+        parallel --line-buffered -X ls -qd --quoting-style=literal --color {}
+    else
+        xargs -r -d '\n' ls -qd --quoting-style=literal --color --
+    fi
 }
 
 # ┌──────────┐
 # │ Handlers │
 # └──────────┘
 
-function do_rg() {
-    rg --files --hidden --follow -- "$cwd" | file_filter | null_filter
+do_rg() {
+    rg --files --hidden --follow -- "${dirs[@]}" |
+        file_filter |
+        null_filter
 }
 
-function do_git() {
-    git ls-files -- "$cwd" | file_filter | null_filter
+do_git() {
+    git ls-files -- "${dirs[@]}" |
+        file_filter |
+        null_filter
 }
 
-function do_fd() {
+do_fd() {
     flags=( )
     if [ "$dirs_only" -eq 1 ]; then
         flags+=( --type d )
@@ -127,11 +162,10 @@ function do_fd() {
     fi
 
     [ "$null" -eq 1 ] && flags+=( --print0 )
-
-    fd --follow -H --color never "${flags[@]}" . -- "$cwd"
+    fd --follow -H --color never "${flags[@]}" . -- "${dirs[@]}"
 }
 
-function do_find() {
+do_find() {
     flags=( )
     if [ "$dirs_only" -eq 1 ]; then
         flags+=( -type d )
@@ -140,8 +174,7 @@ function do_find() {
     fi
 
     [ "$null" -eq 1 ] && flags+=( -print0 )
-
-    find -L "$cwd" -mindepth 1 "${flags[@]}"
+    find -L "${dirs[@]}" -mindepth 1 "${flags[@]}"
 }
 
 # ┌─────────────┐
@@ -150,26 +183,15 @@ function do_find() {
 #
 # Run through available programs and invoke the first handler you find.
 
-function list_project() {
-    if [ "$find_all" -eq 1 ]; then
-        # jump straight to the fallback behaviour
-        do_find
-    elif hash rg; then
-        do_rg
-    elif [ -d .git ] || git git rev-parse --git-dir; then
-        do_git
-    elif hash fd; then
-        do_fd
-    else
-        do_find
-    fi 2>/dev/null
-}
-
-list_project |
-    if [ "$color" -eq 0 ]; then
-        cat # no color, output as is :-(
-    elif command -v parallel >/dev/null 2>&1; then
-        parallel --line-buffered -X ls -qd --quoting-style=literal --color {}
-    else
-        xargs -r -d '\n' ls -qd --quoting-style=literal --color
-    fi
+if [ "$find_all" -eq 1 ]; then
+    do_find
+elif hash rg; then
+    do_rg
+elif [ -d .git ] || git git rev-parse --git-dir; then
+    do_git
+elif hash fd; then
+    do_fd
+else
+    do_find
+fi |
+    color_filter
