ps1 (refactor): move prompt coloring to unique script

diff --git a/programming/scripts/.ps1/bash b/programming/scripts/.ps1/bash
--- a/programming/scripts/.ps1/bash
+++ b/programming/scripts/.ps1/bash
@@ -38,80 +38,11 @@ case "$TERM" in
         fi
 
         _pre_prompt() {
-            # See For More: https://misc.flogisoft.com/bash/tip_colors_and_formatting
-            # Color Codes: \[\e[0;%dm\] % (code)
-            #     * DIM               ~> 0
-            #     * BRIGHT            ~> 1 (for colors in 30s)
-            #     * BOLD              ~> 1 (for colors in 90s)
-            #
-            #     * BLACK             ~> 30
-            #     * RED               ~> 31
-            #     * GREEN             ~> 32
-            #     * YELLOW            ~> 33
-            #     * LIGHT_BLUE        ~> 34
-            #     * PURPLE            ~> 35
-            #     * CYAN              ~> 36
-            #     * WHITE             ~> 37
-            #     * RESTORE           ~> 39
-            #     * DARK GREY         ~> 90
-            #     * LIGHT RED         ~> 91
-            #     * LIGHT GREEN       ~> 92
-            #     * LIGHT YELLOW      ~> 93
-            #     * LIGHT BLUE        ~> 94
-            #     * LIGHT MAGENTA     ~> 95
-            #     * LIGHT CYAN        ~> 96
-            #     * LIGHT WHITE (WTF) ~> 97
-
             local previous_exit_code="$?" user_color="\[\e[0;32m\]"
 
             if [ "${PS1_COLOR_CODED:-0}" = 1 ]; then
-                case "$previous_exit_code" in
-                    1) # catchall for general errors
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    2) # misuse of shell builtins
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    126) # command invoked cannot execute
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    127) # command not found
-                        user_color="\[\e[1;34m\]"
-                    ;;
-                    128) # invalid argument to exit
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    129) # SIGHUP
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    130) # SIGINT
-                        user_color="\[\e[1;33m\]"
-                    ;;
-                    131) # SIGQUIT
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    132) # SIGILL
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    133) # SIGTRAP
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    134) # SIGABRT
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    135) # SIGBUS
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    136) # SIGFPE
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                    137) # SIGKILL
-                        user_color="\[\e[1;35m\]"
-                    ;;
-                    255) # Exit Status Out Of Range
-                        user_color="\[\e[1;31m\]"
-                    ;;
-                esac
+                local new_user_color="$($scripts_path/.ps1/error_colors.sh "$previous_exit_code")"
+                [ $? -eq 0 ] && user_color="$new_user_color" # assign color based on last exit code
             fi
 
             local ps1_pre="$user_color\u@\h \[\e[33m\]\w\[\e[1;34m\]\$(__git_ps1)" ps1_post="\[\e[0m\]λ "
