(autoloads): Add _fzf
A command to automate the usage of FZF_SHELL_OPTS. Essentially this
command subplants fzf for various uses inside of the shell. You can
still use the plain fzf command through `fzf`.

diff --git a/core/autoload/cmds/cd_project_root b/core/autoload/cmds/cd_project_root
--- a/core/autoload/cmds/cd_project_root
+++ b/core/autoload/cmds/cd_project_root
@@ -1,5 +1,6 @@
 # -*- mode: sh -*-
 cd_project_root() {
-    local dest="$(project-root)"
-    cd "$dest" || echo "error: failed to cd: $dest" >&2
+    if local dest="$(project-root)" && [ -n "$dest" ]; then
+        cd "$dest" || echo "error: failed to cd: $dest" >&2
+    fi
 }
