(misc): update
+ Fixed various linting errors.
+ Make vim automatically make directories on save.
+ Update tmux config and default bindings
+ Add tmux command to pipe or cancel pane pipe
+ Fix linting was failing due to leading ./ in lint.ignore

diff --git a/core/autoload/cmds/select_path b/core/autoload/cmds/select_path
--- a/core/autoload/cmds/select_path
+++ b/core/autoload/cmds/select_path
@@ -28,21 +28,19 @@ select_path() {
            printf "%s\n" "${files[@]}" |
                $SELECT_PATH_EDIT_FILE_CMD
        else
-           # Annoying dependence on python3 to get the current terminal fd.
            # This is needed to access and interact with the current terminal
            # in the middle of a pipeline (which select_path is probably called
            # in), and without it some less capable editors like vim or...
            # emacsclient (not emacs though (ノдヽ)) will fail to startup properly.
-           local tty="$(python3 -c '
-import os
-# See [[~/.config/dotfiles/bin/lib/python/terminal.py][terminal.py]]
-try:
-    print(os.ttyname(2))
-except OSError:
-   print("/dev/tty")
-           ')"
-           # shellcheck disable=SC2086
-           xargs -r -d '\n' -a <(printf "%s\n" "${files[@]}") ${VISUAL-${$EDITOR-vi}} >"$tty" <"$tty"
+           #
+           # See [[https://github.com/cute-jumper/epipe/blob/e881004d7d6248fc6a6ea4c197f0bc56acb60583/epipe#L3][here]].
+           local tty=
+           if tty="/dev/$(ps -o tty= -p $$)"; then
+               # shellcheck disable=SC2086,SC2094
+               xargs -r -d '\n' -a <(printf "%s\n" "${files[@]}") ${VISUAL-${$EDITOR-vi}} >"$tty" <"$tty"
+           else
+               echo "select_path: error: failed to read tty" >&2
+           fi
        fi
     fi
 
