(tmux): Add custom leader map
So I didn't notice this in the earlier release but tmux finally added
support for nested keybindings. That means you're no longer limited to
just <leader><key> but can make <leader><key><key> bindings and more.

With this commit I've added a new leader prefix at <leader>x where I've
moved some of my earlier command-oriented bindings (example: fztmuxinator
fuzzy session-attach etc.). I've also migrated away from creating copies
of my autoload scripts to instead sourcing them and modifying certain
commands. This should minimize the amount of duplication between tmux
and my shell.

diff --git a/core/autoload/cmds/select_path b/core/autoload/cmds/select_path
--- a/core/autoload/cmds/select_path
+++ b/core/autoload/cmds/select_path
@@ -6,7 +6,8 @@ select_path() {
     [ -z "$selected" ] && return
 
     if ! local dest="$(readlink -e "$selected")"; then
-        echo "error: failed to read symlink: $selected"
+        echo "error: failed to read symlink: $selected" >&2
+        exit
     fi
 
     if [ -d "$dest" ]; then
