all: misc changes
a bunch of small tweaks here and there:
- added dotbot repository to .gitignore
- added vi like aliases to exit the shell.
- made less search case insensitive and persist marks across sessions.
- added default global node directory to PATH
- install pry alongside ruby. It's a way better debugger.
- enabled syntex support in zathura.
- fixed spawn-term rows and cols flags caused terminal to crash.

diff --git a/programs/tmux/scripts/config.yml b/programs/tmux/scripts/config.yml
--- a/programs/tmux/scripts/config.yml
+++ b/programs/tmux/scripts/config.yml
@@ -1,3 +1,20 @@
+- shell:
+    - description: syncing fzf-tmux
+      quiet: true
+      command: |-
+        if [ -e ./fzf-tmux ]; then
+            :
+        elif which fzf-tmux >/dev/null 2>/dev/null; then
+            ln -s "$(which fzf-tmux)" ./fzf-tmux
+        else
+            if curl -LO https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux; then
+                chmod +x ./fzf-tmux
+            else
+                echo "unable to retrieve fzf-tmux"
+                exit 1
+            fi
+        fi
+
 - link:
     ~/.config/tmux/scripts/attach-session:
     ~/.config/tmux/scripts/manage-windows:
@@ -7,16 +24,3 @@
         path: fzf-tmux
         force: true
         ignore-missing: true
-
-- shell:
-    - description: syncing fzf-tmux
-      quiet: true
-      command: |-
-        ( which fzf-tmux >/dev/null 2>/dev/null || [ -f './fzf-tmux' ] ) && exit 0
-
-        if curl -LO https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux; then
-            chmod +x ./fzf-tmux
-        else
-            echo "unable to retrieve fzf-tmux"
-            exit 1
-        fi
