programs/tmux: add tmux-fzf installation script

diff --git a/programs/tmux/scripts/config.yml b/programs/tmux/scripts/config.yml
--- a/programs/tmux/scripts/config.yml
+++ b/programs/tmux/scripts/config.yml
@@ -3,3 +3,20 @@
     ~/.tmux/scripts/manage-windows:
     ~/.tmux/scripts/run-binding:
     ~/.tmux/scripts/run-command:
+    ~/programming/scripts/fzf-tmux:
+        path: fzf-tmux
+        force: true
+        ignore-missing: true
+
+- shell: 
+    - description: syncing fzf-tmux
+      quiet: true
+      command: |-
+        ( which fzf-tmux >/dev/null 2>/dev/null || [ -f './fzf-tmux' ] ) && exit 0
+
+        if curl -LO https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-tmux; then
+            chmod +x ./fzf-tmux
+        else
+            echo "unable to retrieve fzf-tmux"
+            exit 1
+        fi
