(zshell): switch to asynchronous prompt constructor
Now I'm using [[https://github.com/mafredri/zsh-async][zsh-async]] for asynchronously populating my shell prompt.
It's noticably faster, although there is a mild lag where something
gets pushed into my prompt after a small change.

I've also reduced my git-prompt script immensely, it just does the
bare minimum of what it needs to. I.E. showing branch and/or rebase
information.

diff --git a/core/sh/prompt/bash b/core/sh/prompt/bash
--- a/core/sh/prompt/bash
+++ b/core/sh/prompt/bash
@@ -20,30 +20,30 @@
 #                   exit code of the last command.
 #
 
-git_prompt_path="$SCRIPTS_DIR/.ps1/git-prompt.sh"
-
+git_prompt_path="$XDG_CONFIG_HOME/prompt/bin/git-prompt"
 if ! hash __git_ps1 1>/dev/null 2>&1; then
-    if [ -f "$git_prompt_path" ]; then
-        . "$git_prompt_path" # source git prompt script to define __git_ps1
-    else
-        echo "bash_ps1(error) : git prompt script not found: $git_prompt_path" >&2
-        __git_ps1() { echo ""; } # when not given, git PS1 just shows an empty string
-    fi
+  if [ -f "$git_prompt_path" ]; then
+    ENTRY_POINT='true' . "$git_prompt_path" # source git prompt script to define __git_ps1
+  else
+    echo "bash_ps1(error) : git prompt script not found: $git_prompt_path" >&2
+    __git_ps1() { echo ""; } # when not given, git PS1 just shows an empty string
+  fi
 fi
+unset git_prompt_path
 
 _pre_prompt() {
-    local previous_exit_code="$?" user_color="\[\e[0;1;32m\]"
+  local previous_exit_code="$?" user_color="\[\e[0;1;32m\]"
 
-    if [ "${PS1_COLOR_CODED:-0}" = 1 ]; then
-        local new_user_color="$($scripts_path/.ps1/error_colors.sh "$previous_exit_code")"
-        [ $? -eq 0 ] && user_color="$new_user_color" # assign color based on last exit code
-    fi
+  if [ "${PS1_COLOR_CODED:-0}" = 1 ]; then
+    local new_user_color="$($XDG_CONFIG_HOME/prompt/bin/error_colors "$previous_exit_code")"
+    [ $? -eq 0 ] && user_color="$new_user_color" # assign color based on last exit code
+  fi
 
-    local ps1_pre="$user_color\u@\h \[\e[0;1;33m\]\w\[\e[1;34m\]\$(__git_ps1)" ps1_post="\[\e[0;1m\]λ "
-    if [ "${PS1_INLINE:-0}" = 1 ]; then ps1_pre="$ps1_pre "; else ps1_pre="$ps1_pre"$'\n'; fi
-    PS1="$ps1_pre$ps1_post\[\e[0m\]"
+  local ps1_pre="$user_color\u@\h \[\e[0;1;33m\]\w\[\e[1;34m\] (\$(__git_ps1))" ps1_post="\[\e[0;1m\]λ "
+  if [ "${PS1_INLINE:-0}" = 1 ]; then ps1_pre="$ps1_pre "; else ps1_pre="$ps1_pre"$'\n'; fi
+  PS1="$ps1_pre$ps1_post\[\e[0m\]"
 
-    return "$previous_exit_code"
+  return "$previous_exit_code"
 }
 
 PROMPT_COMMAND='_pre_prompt'
