deploy: (ls-project): prefix output with cwd and follow symlinks
Ran into an issue where fzf_select_all didn't offer symlinks as
potential completion candidates... fixed it by making each program in
ls-project follow symlinks (there doesn't seem to be a way to follow
symlinks while specifying not to recurse into them).

Then I realised if you supply a path to ls-project, eg. ~/.config/
ls-project doesn't include that path in the output making file
selection broken. Fixed by passing the supplied path (or .) to each
program instead of changing the cwd of the scripts shell.

Everythings working now :-). d0aea857f08ec23bf09220247116366155566084

diff --git a/core/shortcuts/commands/fzf_select b/core/shortcuts/commands/fzf_select
--- a/core/shortcuts/commands/fzf_select
+++ b/core/shortcuts/commands/fzf_select
@@ -1,13 +1,18 @@
 #!/usr/bin/env sh
 fzf_select() {
-    dest="$(ls-project "${fzf_select_flags:-"-z"}" "$@" | fzf --read0 --no-multi --preview 'preview {}' --preview-window=25%)" &&
-        if [ -d "$dest" ]; then
-            # shellcheck disable=SC2164
-            cd "$dest" || echo "error: failed to cd: $dest" >&2
-        elif [ -f "$dest" ]; then
-            ${VISUAL:-${EDITOR:-vi}} "$dest"
-        else
-            echo "error: don't know how to handle: $dest" >&2
-        fi
-    unset dest
+    local selected="$(ls-project "${fzf_select_flags:-"-z"}" "$@" | fzf --read0 --no-multi --preview 'preview {}' --preview-window=25%)"
+    [ -z "$selected" ] && return
+
+    if ! local dest="$(readlink -e "$selected")"; then
+        echo "error: failed to read symlink: $selected"
+    fi
+
+    if [ -d "$dest" ]; then
+        # shellcheck disable=SC2164
+        cd "$dest" || echo "error: failed to cd: $dest" >&2
+    elif [ -f "$dest" ]; then
+        ${VISUAL:-${EDITOR:-vi}} "$dest"
+    else
+        echo "error: don't know how to handle: $dest" >&2
+    fi
 }
