(misc): Fix linter errors and pass scripts through formatters

diff --git a/prog/lf/cmds/paste-links b/prog/lf/cmds/paste-links
--- a/prog/lf/cmds/paste-links
+++ b/prog/lf/cmds/paste-links
@@ -18,19 +18,23 @@ EOF
 reverse=0
 while getopts 'hr' OPTION; do
   case "$OPTION" in
-    r) reverse=1 ;;
-    h) echo "$HELP"
-       exit 0 ;;
-    \?) echo "$USAGE"
-        exit 1 ;;
+  r) reverse=1 ;;
+  h)
+    echo "$HELP"
+    exit 0
+    ;;
+  \?)
+    echo "$USAGE"
+    exit 1
+    ;;
   esac
 done
 
 # All non-empty files in the marked file list
 files=$(sed --quiet -e '/^$/d' -e p "$XDG_DATA_HOME/lf/files")
 
-read -r operation <<< "$files"
-files=$(tail -n +2 <<< "$files")
+read -r operation <<<"$files"
+files=$(tail -n +2 <<<"$files")
 
 if [ -z "$files" ]; then
   lf -remote "send $id echoerr \"No files in cut list\""
@@ -47,7 +51,7 @@ else
 fi
 
 if [ "$reverse" -eq 0 ]; then
-  xargs -d '\n' -r ln "$link_type" -vt "$(dirname "$f")" <<< "$files"
+  xargs -d '\n' -r ln "$link_type" -vt "$(dirname "$f")" <<<"$files"
   lf -remote "send $id :clear"$'\n'"send $id :load"
 else
   failed=$(mktemp)
@@ -57,14 +61,14 @@ else
   while read -r fpath; do
     base="$(basename "$fpath")"
     if [ -e "$dir/$base" ] || ! {
-           mv -n -t "$dir" "$fpath" &&
-             ln "$link_type" -vt "$(dirname "$fpath")" "$dir/$base"
-         }; then
+      mv -n -t "$dir" "$fpath" &&
+        ln "$link_type" -vt "$(dirname "$fpath")" "$dir/$base"
+    }; then
       lf -remote "send $id echoerr \"Destination already exists: $fpath\""
-      echo "$fpath" > "$failed"
+      echo "$fpath" >"$failed"
     fi
-  done <<< "$files"
+  done <<<"$files"
 
-  printf "%s\n%s\n" "$operation" "$(cat "$failed")" > "$XDG_DATA_HOME/lf/files"
+  printf "%s\n%s\n" "$operation" "$(cat "$failed")" >"$XDG_DATA_HOME/lf/files"
   lf -remote "send :sync"$'\n'"send $id :load"
 fi
diff --git a/prog/polybar/cmds/polywin b/prog/polybar/cmds/polywin
--- a/prog/polybar/cmds/polywin
+++ b/prog/polybar/cmds/polywin
@@ -7,7 +7,7 @@
 # scripts in the polybar format of the win-list command.
 
 max_window_count=10
-ignore_window_classes=( Plasmashell Polybar Conky Gmrun )
+ignore_window_classes=(Plasmashell Polybar Conky Gmrun)
 
 usage() {
   echo "Usage: win-list {OPERATION} [OPTS [OPTS...]]"
@@ -199,11 +199,13 @@ if [ "$#" -eq 0 ]; then
 fi
 
 case "$1" in
-  usage|help|win-list|raise|close)
-    "$@"
-    exit "$?" ;;
-  *)
-    echo "error: polywin: unknown operation $1" >&2
-    usage >&2
-    exit 1 ;;
+usage | help | win-list | raise | close)
+  "$@"
+  exit "$?"
+  ;;
+*)
+  echo "error: polywin: unknown operation $1" >&2
+  usage >&2
+  exit 1
+  ;;
 esac
