misc: update msys compatability
I recently reinstalled windows and run into a bunch of issues with my
dotfile installation. This commit addresses those. Issues encountered:

* msys bash wasn't inheriting my windows PATH variable, meaning it was
  unable to access windows programs such as chocolatey, making dotfile
  installation kind of fruitless.
* chocolatey was crashing because of interference between the TEMP,
  TMP, temp and tmp environment variables. Go figure.
* winpty installer was referencing a bash location that doesn't exist
  on initial install. -> switched to using /usr/bin/env.
* And most glaringly... msys wasn't considered a windows environment
  in my setup/dotbot and setup/platform scripts. TODO come up with a
  clean script for dotfiles.

diff --git a/dist/msys.yml b/dist/msys.yml
--- a/dist/msys.yml
+++ b/dist/msys.yml
@@ -21,7 +21,19 @@
           exit 1
         fi
 
-        sed -i -e 's/db_home: cygwin desc/db_home windows/' "$conf_file"
+        sed -i -e 's/db_home: cygwin desc/db_home: windows/' "$conf_file"
+
+- shell:
+    - description: allowing windows PATH inheritance
+      quiet: true
+      command: |-
+        conf_file="c:/tools/msys64/msys2_shell.cmd"
+        if ! [ -f "$conf_file" ]; then
+          echo "failed to set PATH inheritance, conf file doesn't exist" >&2
+          exit 1
+        fi
+
+        sed -i -e 's/rem \(set MSYS2_PATH_TYPE=inherit\)/\1/' "$conf_file"
 
 - packages:
     msys:
@@ -39,7 +51,7 @@
       command: |-
         [ -e "c:/tools/msys64/usr/local/bin/winpty.exe" ] && exit 0
 
-        c:/tools/msys64/bin/bash << "EOF"
+        c:/tools/msys64/usr/bin/env bash << "EOF"
         cd $(mktemp -d)
         git clone https://github.com/rprichard/winpty winpty
         cd winpty
